import Head from "next/head";
import Image from "next/image";
import BlockTab from "../components/BlockTab";
import Header from "../components/Header";
import SideBar from "../components/SideBar";
import StatCards from "../components/StatCards";
import Welcome from "../components/Welcome";
import { getEthPrice } from "../utils/getEthPrice";
import { getMarketCap } from "../utils/getMarketCap";

import TxTab from "../components/TxTab";
import { useState, useEffect } from "react";

export default function Home({ ethPrice, marketCap }) {
  return (
    <div className="min-h-screen flex flex-col flex-auto flex-shrink-0 antialiased bg-base  ">
      <Head>
        <title>Block Explorer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* Header */}
      <Header />
      <div className="h-full ml-14 mt-14 mb-10 md:ml-64">
        <Welcome />

        {/* SideBar */}
        <SideBar />

        {/* Stat Cards */}
        <StatCards price={ethPrice} market={marketCap} />

        {/* Block Tab */}
        <BlockTab />

        {/* Transaction Tab */}
        <TxTab />
      </div>
    </div>
  );
}
export async function getStaticProps() {
  const ethPrice = await getEthPrice();
  const marketCap = await getMarketCap();

  return {
    props: { ethPrice, marketCap },
    revalidate: 5,
  };
}
